# Dependencies
#markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

# Custom vars

social:
  github:	https://github.com/onigoetz
  gplus: https://plus.google.com/u/1/112011413401921026329/posts
  linkedin: http://ch.linkedin.com/in/stephanegoetz
  twitter: http://twitter.com/onigoetz

projects:
  - name: "Projects"
    description: "Projects I'm involved in"
    projects:
     - name: Daux.io
       github: justinwalsh/daux.io
       status: active
       documentation: http://daux.io
       description:
        - Daux.io is a documentation generator that uses a simple folder structure and Markdown files to create custom documentation on the fly.
       technologies:
        - php
       badges:
         - <span class=github-btn data-user=justinwalsh data-repo=daux.io data-count=true data-type=watch></span>
         - <span class=github-btn data-user=justinwalsh data-repo=daux.io data-count=true data-type=fork></span>
     - name: ST-JS Strongly Typed JavaScript
       github: st-js/st-js
       status: active
       documentation: http://www.st-js.org/
       description:
        - A Java to Javascript transpiler, Borrow Java's syntax to write Javascript
       technologies:
        - java
       badges:
         - <span class=github-btn data-user=st-js data-repo=st-js data-count=true data-type=watch></span>
         - <span class=github-btn data-user=st-js data-repo=st-js data-count=true data-type=fork></span>
     - name: Rocket Propelled Tortoise - Core
       github: RocketPropelledTortoise/Core
       documentation: http://rocketpropelledtortoise.github.io/Docs/
       status: wip
       description:
        - A content management framework, provides a backend to store content, you write the frontend the way you want.
       technologies:
        - laravel
        - php
       badges:
        - <span class=github-btn data-user=RocketPropelledTortoise data-repo=Core data-count=true data-type=watch></span>
        - <span class=github-btn data-user=RocketPropelledTortoise data-repo=Core data-count=true data-type=fork></span>
        - <a href=https://travis-ci.org/RocketPropelledTortoise/Core><img src="https://img.shields.io/travis/RocketPropelledTortoise/Core/master.svg?style=flat" alt="Build Status"></a>
        - <a href=https://scrutinizer-ci.com/g/RocketPropelledTortoise/Core><img src="https://img.shields.io/scrutinizer/g/RocketPropelledTortoise/Core.svg?style=flat" alt="Code Quality"></a>
        - <a href="https://packagist.org/packages/rocket/core"><img alt="Total Downloads" src="http://img.shields.io/packagist/dt/rocket/core.svg?style=flat"></a>
       projects:
         - name: Entities
           status: wip
           description:
            - Content management API, store, update and delete entities.
           technologies:
            - laravel
            - php
         - name: Taxonomy
           github: RocketPropelledTortoise/Taxonomy
           status: active
           description:
            - Tag your content the way you want with hierarchical taxonomies
           technologies:
            - laravel
            - php
         - name: Translation
           github: RocketPropelledTortoise/Translation
           status: active
           description:
            - Interface translation simplified, stored in database, cached in files for speed
           technologies:
            - laravel
            - php
         - name: Utilties
           github: RocketPropelledTortoise/Utilities
           status: wip
           description:
            - Helper classes ... what can I say more ?
           technologies:
            - laravel
            - php
     - name: Rocket Propelled Tortoise - UI
       github: RocketPropelledTortoise/UI
       documentation: http://rocketpropelledtortoise.github.io/Docs/
       status: wip
       description:
        - The user interface for the Core components of Rocket CMS
       technologies:
        - laravel
        - php
        - js
       badges:
        - <span class=github-btn data-user=RocketPropelledTortoise data-repo=UI data-count=true data-type=watch></span>
        - <span class=github-btn data-user=RocketPropelledTortoise data-repo=UI data-count=true data-type=fork></span>
        - <a href=https://travis-ci.org/RocketPropelledTortoise/UI><img src="https://img.shields.io/travis/RocketPropelledTortoise/UI/master.svg?style=flat" alt="Build Status"></a>
        - <a href=https://scrutinizer-ci.com/g/RocketPropelledTortoise/UI><img src="https://img.shields.io/scrutinizer/g/RocketPropelledTortoise/UI.svg?style=flat" alt="Code Quality"></a>
        - <a href="https://packagist.org/packages/rocket/ui"><img alt="Total Downloads" src="http://img.shields.io/packagist/dt/rocket/ui.svg?style=flat"></a>
       projects:
         - name: Assets
           github: RocketPropelledTortoise/Assets
           status: wip
           description:
            - Asset management simplified, integrates with <code>script</code>
           technologies:
            - laravel
            - php
         - name: Forms
           github: RocketPropelledTortoise/Forms
           status: wip
           description:
            - Create form fields easily with a clean and fluid syntax
           technologies:
            - laravel
            - php
         - name: Foundation
           github: RocketPropelledTortoise/Foundation
           status: wip
           description:
            - All views and scripts for the UI Base
           technologies:
            - laravel
            - php
         - name: Script
           github: RocketPropelledTortoise/Script
           status: active
           description:
            - Enqueue javascript to put at the end of the page
           technologies:
            - laravel
            - php
            - js
         - name: Table
           github: RocketPropelledTortoise/Table
           status: active
           description:
            - An elegant table helper
           technologies:
            - laravel
            - php
         - name: Taxonomy UI
           status: wip
           description:
            - Taxonomy edition UI
           technologies:
            - laravel
            - php
         - name: Translation UI
           status: wip
           description:
            - Translation edition UI
           technologies:
            - laravel
            - php
         - name: Content UI
           status: wip
           description:
            - Manage your contents, create, edit, translate...
           technologies:
            - laravel
            - php
  - name: "Libraries"
    projects:
      - name: Imagecache
        github: onigoetz/imagecache
        status: active
        description:
         - Resize your images with your predefined presets.
        technologies:
         - laravel
         - slim
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=imagecache data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=imagecache data-count=true data-type=fork></span><br />
         - <a href="https://travis-ci.org/onigoetz/imagecache"><img alt="Build Status" src="http://img.shields.io/travis/onigoetz/imagecache.svg?style=flat"></a>
         - <a href=https://scrutinizer-ci.com/g/onigoetz/imagecache><img src="https://img.shields.io/scrutinizer/g/onigoetz/imagecache.svg?style=flat" alt="Code Quality"></a>
         - <a href="https://packagist.org/packages/onigoetz/imagecache"><img alt="Latest Stable Version" src="http://img.shields.io/packagist/v/onigoetz/imagecache.svg?style=flat"></a>
         - <a href="https://packagist.org/packages/onigoetz/imagecache"><img alt="Total Downloads" src="http://img.shields.io/packagist/dt/onigoetz/imagecache.svg?style=flat"></a>
      - name: Deployer
        github: onigoetz/deployer
        documentation: /deployer
        status: active
        description:
         - Deploy your applications to a number of servers, connect by SSH, clone with GIT.
        technologies:
         - laravel
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=deployer data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=deployer data-count=true data-type=fork></span><br />
         - <a href="https://travis-ci.org/onigoetz/deployer"><img alt="Build Status" src="http://img.shields.io/travis/onigoetz/deployer.svg?style=flat"></a>
         - <a href=https://scrutinizer-ci.com/g/onigoetz/deployer><img src="https://img.shields.io/scrutinizer/g/onigoetz/deployer.svg?style=flat" alt="Code Quality"></a>
         - <a href="https://packagist.org/packages/onigoetz/deployer"><img alt="Latest Stable Version" src="http://img.shields.io/packagist/v/onigoetz/deployer.svg?style=flat"></a>
         - <a href="https://packagist.org/packages/onigoetz/deployer"><img alt="Total Downloads" src="http://img.shields.io/packagist/dt/onigoetz/deployer.svg?style=flat"></a>
      - name: jQuery autocomplete
        github: onigoetz/jquery.autocomplete
        status: unmaintained
        description:
         - Drop-in replacement for jQuery UI autocomplete
        technologies:
         - jquery
         - js
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=jquery.autocomplete data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=jquery.autocomplete data-count=true data-type=fork></span>
      - name: fpdi_tcpdf
        github: onigoetz/fpdi_tcpdf
        status: abandoned
        description:
         - Use fpdi with TCPDF, PSR-4 compatible
         - 'Deprecated, now that there is an official repository : <a href="https://packagist.org/packages/setasign/fpdi-tcpdf">https://packagist.org/packages/setasign/fpdi-tcpdf</a>'
        technology:
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=fpdi_tcpdf data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=fpdi_tcpdf data-count=true data-type=fork></span>
      - name: Laravel Profiler
        github: onigoetz/profiler
        status: abandoned
        description:
         - Profile your PHP applications, get useful insights on your code.
        technologies:
         - laravel
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=profiler data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=profiler data-count=true data-type=fork></span>
      - name: ST-JS React Bridge
        github: onigoetz/react-bridge
        status: active
        description:
         - The ST-JS bridge to reactJS
        technologies:
         - java
         - js
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=react-bridge data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=react-bridge data-count=true data-type=fork></span>
      - name: jQuery XHRFilter
        github: onigoetz/jquery-xhrfilter
        status: active
        description:
         - Intercept ajax requests to add custom logic, like password confirmation.
        technologies:
         - jquery
         - js
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=jquery-xhrfilter data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=jquery-xhrfilter data-count=true data-type=fork></span>
      - name: Prediggo PHP API
        github: onigoetz/prediggo-php
        status: unmaintained
        description:
         - The PHP Implementation of the Prediggo API. PSR-1 Compatible
        technologies:
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=prediggo-php data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=prediggo-php data-count=true data-type=fork></span>
  - name: "Small Projects"
    description: "A list of small projects, experiments or utilities"
    projects:
      - name: Comics Reader
        github: onigoetz/Comics-Reader
        status: active
        description:
         - Read your comic books on a tablet. Install it on your server and enjoy
        technologies:
         - jquery
         - js
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=Comics-Reader data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=Comics-Reader data-count=true data-type=fork></span>
      - name: Photo Gallery
        github: onigoetz/PhotoGallery
        status: active
        description:
         - Photo Gallery, with React, ES2015, Hot Reload
        technologies:
         - react
         - js
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=PhotoGallery data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=PhotoGallery data-count=true data-type=fork></span>
      - name: Reactavel
        github: onigoetz/Reactavel
        status: wip
        description:
         - What if PHP could run as an application server ?
         - This is the experiment I'm running with Lumen and ReactPHP
        technologies:
         - laravel
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=Reactavel data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=Reactavel data-count=true data-type=fork></span>
      - name: Dyn53
        github: onigoetz/dyn53
        status: unmaintained
        description:
         - A small utility to update a DNS record according to the current public IP address, in a Amazon Route 53 Zone.
         - works as a replacement to DynDns
        technologies:
         - php
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=dyn53 data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=dyn53 data-count=true data-type=fork></span>
      - name: Github Buttons
        github: onigoetz/github-buttons
        status: unmaintained
        description:
         - A faster implementation of Github Buttons
         - Used on this website ;-)
        technologies:
         - js
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=github-buttons data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=github-buttons data-count=true data-type=fork></span>
      - name: Halloween JÃ¤gerbomber
        github: onigoetz/halloween-jagerbomber
        status: unmaintained
        description:
         - Code for a countdown timer on a Raspberry pi with a 4x7 segment display
         - Once at zero it ... resets
        technologies:
         - python
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=halloween-jagerbomber data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=halloween-jagerbomber data-count=true data-type=fork></span>
  - name: "Plugins"
    description: "Wordpress <small>Blogging platform</small>"
    projects:
      - name: PHPBB Single Sign On
        url: http://wordpress.org/plugins/phpbb-single-sign-on/
        status: abandoned
        description:
         - Connect to a wordpress blog and PHPBB Forum at the same time with the same login.
         - I don't recommend using it as there are some security issues with it.
        technologies:
         - wordpress
         - php
      - name: eCSStender
        url: http://wordpress.org/plugins/ecsstender-take-control-of-your-css/
        status: abandoned
        description:
         - The <a href="http://ecsstender.org/">ecsstender</a> library as a wordpress plugin
        technologies:
         - wordpress
         - php
         - js
  - name: "Plugins"
    description: "Sentry <small>Error logging platform</small>"
    projects:
      - name: Sentry-nagios
        github: onigoetz/Sentry-nagios
        status: abandoned
        description:
         - Connect sentry to nagios, each project can trigger a custom alert
        technologies:
         - python
        badges:
         - <span class=github-btn data-user=onigoetz data-repo=sentry-nagios data-count=true data-type=watch></span>
         - <span class=github-btn data-user=onigoetz data-repo=sentry-nagios data-count=true data-type=fork></span>
